apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
data:
  influxdb_username: bmV3bWFu
  influxdb_password: VHBoYWxvOGM=
  influxdb_org: aDRo
  influxdb_bucket: YXBpX3Jlc3VsdHM=
  influxdb_token: PDMzVWJAdkA=
  influxdb_mode: c2V0dXA=